// Genişletilmiş kelime setleri - Her seviyede 20+ kelime
export const FLASHCARD_DATA_EXTENDED: Record<string, Record<string, any[]>> = {
  en: {
    A1: [
      { word: 'Hello', translation: 'Merhaba', icon: '👋', example: 'Hello, how are you?' },
      { word: 'Thank you', translation: 'Teşekkür ederim', icon: '🙏', example: 'Thank you for your help!' },
      { word: 'Sorry', translation: 'Özür dilerim', icon: '😔', example: 'I\'m sorry for being late.' },
      { word: 'Please', translation: 'Lütfen', icon: '🥺', example: 'Can you help me, please?' },
      { word: 'Goodbye', translation: 'Hoşça kal', icon: '👋', example: 'Goodbye, see you tomorrow!' },
      { word: 'Yes', translation: 'Evet', icon: '✅', example: 'Yes, I agree with you.' },
      { word: 'No', translation: 'Hayır', icon: '❌', example: 'No, I don\'t want that.' },
      { word: 'Water', translation: 'Su', icon: '💧', example: 'Can I have some water?' },
      { word: 'Food', translation: 'Yemek', icon: '🍕', example: 'The food is delicious!' },
      { word: 'Friend', translation: 'Arkadaş', icon: '👥', example: 'She is my best friend.' },
      { word: 'Family', translation: 'Aile', icon: '👨‍👩‍👧', example: 'I love my family.' },
      { word: 'House', translation: 'Ev', icon: '🏠', example: 'This is my house.' },
      { word: 'Dog', translation: 'Köpek', icon: '🐕', example: 'I have a dog.' },
      { word: 'Cat', translation: 'Kedi', icon: '🐈', example: 'The cat is sleeping.' },
      { word: 'Good', translation: 'İyi', icon: '👍', example: 'Have a good day!' },
      { word: 'Bad', translation: 'Kötü', icon: '👎', example: 'That\'s a bad idea.' },
      { word: 'Help', translation: 'Yardım', icon: '🆘', example: 'I need help!' },
      { word: 'Love', translation: 'Sevmek', icon: '❤️', example: 'I love you.' },
      { word: 'Happy', translation: 'Mutlu', icon: '😊', example: 'I\'m so happy today!' },
      { word: 'Sad', translation: 'Üzgün', icon: '😢', example: 'Why are you sad?' },
      { word: 'Big', translation: 'Büyük', icon: '🔷', example: 'That\'s a big house!' },
      { word: 'Small', translation: 'Küçük', icon: '🔹', example: 'This is a small car.' },
      { word: 'Hot', translation: 'Sıcak', icon: '🔥', example: 'The coffee is hot.' },
      { word: 'Cold', translation: 'Soğuk', icon: '❄️', example: 'It\'s cold outside.' },
      { word: 'Old', translation: 'Yaşlı', icon: '👴', example: 'My grandfather is old.' },
    ],
    A2: [
      { word: 'Appreciate', translation: 'Takdir etmek', icon: '💖', example: 'I appreciate your help.' },
      { word: 'Understand', translation: 'Anlamak', icon: '🧠', example: 'Do you understand the question?' },
      { word: 'Important', translation: 'Önemli', icon: '⭐', example: 'This is very important!' },
      { word: 'Different', translation: 'Farklı', icon: '🔄', example: 'Everyone is different.' },
      { word: 'Explain', translation: 'Açıklamak', icon: '💬', example: 'Can you explain this to me?' },
      { word: 'Beautiful', translation: 'Güzel', icon: '🌺', example: 'What a beautiful day!' },
      { word: 'Difficult', translation: 'Zor', icon: '😓', example: 'This test is difficult.' },
      { word: 'Easy', translation: 'Kolay', icon: '😌', example: 'The exam was easy.' },
      { word: 'Learn', translation: 'Öğrenmek', icon: '📚', example: 'I want to learn English.' },
      { word: 'Teach', translation: 'Öğretmek', icon: '👨‍🏫', example: 'Can you teach me?' },
      { word: 'Remember', translation: 'Hatırlamak', icon: '🧠', example: 'I remember you!' },
      { word: 'Forget', translation: 'Unutmak', icon: '🤔', example: 'Don\'t forget your keys.' },
      { word: 'Busy', translation: 'Meşgul', icon: '⏰', example: 'I\'m busy right now.' },
      { word: 'Free', translation: 'Boş', icon: '🆓', example: 'Are you free tomorrow?' },
      { word: 'Tired', translation: 'Yorgun', icon: '😴', example: 'I feel tired today.' },
      { word: 'Strong', translation: 'Güçlü', icon: '💪', example: 'He is very strong.' },
      { word: 'Weak', translation: 'Zayıf', icon: '😞', example: 'I feel weak.' },
      { word: 'Fast', translation: 'Hızlı', icon: '⚡', example: 'That car is fast!' },
      { word: 'Slow', translation: 'Yavaş', icon: '🐢', example: 'Please speak slowly.' },
      { word: 'Question', translation: 'Soru', icon: '❓', example: 'I have a question.' },
      { word: 'Answer', translation: 'Cevap', icon: '💡', example: 'Do you know the answer?' },
      { word: 'Problem', translation: 'Sorun', icon: '⚠️', example: 'We have a problem.' },
      { word: 'Solution', translation: 'Çözüm', icon: '✅', example: 'I found the solution!' },
      { word: 'Interesting', translation: 'İlginç', icon: '🤨', example: 'That\'s an interesting story.' },
      { word: 'Boring', translation: 'Sıkıcı', icon: '😴', example: 'The movie was boring.' },
    ],
    B1: [
      { word: 'Achieve', translation: 'Başarmak', icon: '🎯', example: 'You can achieve your goals.' },
      { word: 'Consider', translation: 'Düşünmek', icon: '🤔', example: 'I will consider your offer.' },
      { word: 'Benefit', translation: 'Fayda', icon: '✨', example: 'Exercise has many benefits.' },
      { word: 'Opportunity', translation: 'Fırsat', icon: '🚪', example: 'This is a great opportunity!' },
      { word: 'Challenge', translation: 'Meydan okuma', icon: '💪', example: 'Learning English is a challenge.' },
      { word: 'Development', translation: 'Gelişim', icon: '📈', example: 'Child development is important.' },
      { word: 'Experience', translation: 'Deneyim', icon: '🎓', example: 'I have 5 years of experience.' },
      { word: 'Knowledge', translation: 'Bilgi', icon: '📖', example: 'Knowledge is power.' },
      { word: 'Skill', translation: 'Beceri', icon: '🛠️', example: 'Communication is a valuable skill.' },
      { word: 'Success', translation: 'Başarı', icon: '🏆', example: 'Hard work leads to success.' },
      { word: 'Failure', translation: 'Başarısızlık', icon: '❌', example: 'Learn from your failures.' },
      { word: 'Improve', translation: 'İyileştirmek', icon: '⬆️', example: 'I want to improve my English.' },
      { word: 'Progress', translation: 'İlerleme', icon: '📊', example: 'You\'re making great progress!' },
      { word: 'Effort', translation: 'Çaba', icon: '💯', example: 'Success requires effort.' },
      { word: 'Patience', translation: 'Sabır', icon: '⏳', example: 'Learning takes patience.' },
      { word: 'Practice', translation: 'Pratik', icon: '🎯', example: 'Practice makes perfect.' },
      { word: 'Purpose', translation: 'Amaç', icon: '🎯', example: 'What\'s your purpose?' },
      { word: 'Decision', translation: 'Karar', icon: '🤔', example: 'Make a wise decision.' },
      { word: 'Choice', translation: 'Seçim', icon: '🔀', example: 'You have a choice.' },
      { word: 'Method', translation: 'Yöntem', icon: '📋', example: 'This is the best method.' },
      { word: 'Process', translation: 'Süreç', icon: '⚙️', example: 'Trust the process.' },
      { word: 'Result', translation: 'Sonuç', icon: '✅', example: 'The results are positive.' },
      { word: 'Approach', translation: 'Yaklaşım', icon: '🎯', example: 'Try a different approach.' },
      { word: 'Strategy', translation: 'Strateji', icon: '♟️', example: 'We need a new strategy.' },
      { word: 'Goal', translation: 'Hedef', icon: '🎯', example: 'Set realistic goals.' },
    ],
    B2: [
      { word: 'Efficient', translation: 'Verimli', icon: '⚡', example: 'This method is very efficient.' },
      { word: 'Consequence', translation: 'Sonuç', icon: '🔗', example: 'Every action has consequences.' },
      { word: 'Significant', translation: 'Önemli, anlamlı', icon: '🌟', example: 'This is a significant discovery.' },
      { word: 'Adapt', translation: 'Uyum sağlamak', icon: '🦎', example: 'We must adapt to changes.' },
      { word: 'Perspective', translation: 'Bakış açısı', icon: '👁️', example: 'Everyone has a different perspective.' },
      { word: 'Analyze', translation: 'Analiz etmek', icon: '🔬', example: 'Let\'s analyze the data.' },
      { word: 'Evaluate', translation: 'Değerlendirmek', icon: '📊', example: 'We need to evaluate the results.' },
      { word: 'Implement', translation: 'Uygulamak', icon: '⚙️', example: 'Let\'s implement this plan.' },
      { word: 'Establish', translation: 'Kurmak', icon: '🏢', example: 'We need to establish rules.' },
      { word: 'Maintain', translation: 'Sürdürmek', icon: '🔧', example: 'Maintain good relationships.' },
      { word: 'Enhance', translation: 'Geliştirmek', icon: '✨', example: 'This will enhance your skills.' },
      { word: 'Demonstrate', translation: 'Göstermek', icon: '👉', example: 'Let me demonstrate how it works.' },
      { word: 'Contribute', translation: 'Katkıda bulunmak', icon: '🤝', example: 'Everyone should contribute.' },
      { word: 'Participate', translation: 'Katılmak', icon: '🙋', example: 'Please participate in the discussion.' },
      { word: 'Collaborate', translation: 'İşbirliği yapmak', icon: '👥', example: 'We need to collaborate on this.' },
      { word: 'Negotiate', translation: 'Müzakere etmek', icon: '🤝', example: 'Let\'s negotiate the terms.' },
      { word: 'Investigate', translation: 'Araştırmak', icon: '🔍', example: 'They will investigate the case.' },
      { word: 'Determine', translation: 'Belirlemek', icon: '🎯', example: 'We must determine the cause.' },
      { word: 'Indicate', translation: 'Belirtmek', icon: '👆', example: 'The results indicate success.' },
      { word: 'Illustrate', translation: 'Göstermek', icon: '📊', example: 'This example illustrates the point.' },
      { word: 'Emphasize', translation: 'Vurgulamak', icon: '‼️', example: 'I want to emphasize this point.' },
      { word: 'Acknowledge', translation: 'Kabul etmek', icon: '✅', example: 'We acknowledge the problem.' },
      { word: 'Recognize', translation: 'Tanımak', icon: '👀', example: 'I recognize this pattern.' },
      { word: 'Facilitate', translation: 'Kolaylaştırmak', icon: '🔓', example: 'This will facilitate learning.' },
      { word: 'Integrate', translation: 'Entegre etmek', icon: '🔗', example: 'We need to integrate these systems.' },
    ],
    C1: [
      { word: 'Inevitable', translation: 'Kaçınılmaz', icon: '⏰', example: 'Change is inevitable.' },
      { word: 'Comprehend', translation: 'Kavramak', icon: '🧩', example: 'It\'s hard to comprehend the complexity.' },
      { word: 'Profound', translation: 'Derin, etkileyici', icon: '🌊', example: 'He had a profound impact on society.' },
      { word: 'Ambiguous', translation: 'Belirsiz, muğlak', icon: '❓', example: 'The message was ambiguous.' },
      { word: 'Resilient', translation: 'Dayanıklı', icon: '🛡️', example: 'She is very resilient under pressure.' },
      { word: 'Contentious', translation: 'Tartışmalı', icon: '⚔️', example: 'This is a contentious issue.' },
      { word: 'Intricate', translation: 'Karmaşık', icon: '🕸️', example: 'The design is intricate.' },
      { word: 'Eloquent', translation: 'Belagatli', icon: '🗣️', example: 'She gave an eloquent speech.' },
      { word: 'Meticulous', translation: 'Titiz', icon: '🔍', example: 'He is meticulous in his work.' },
      { word: 'Pragmatic', translation: 'Pragmatik', icon: '⚙️', example: 'We need a pragmatic solution.' },
      { word: 'Compelling', translation: 'İlgi çekici', icon: '🎭', example: 'That\'s a compelling argument.' },
      { word: 'Substantial', translation: 'Önemli', icon: '💰', example: 'There is substantial evidence.' },
      { word: 'Detrimental', translation: 'Zararlı', icon: '☠️', example: 'Smoking is detrimental to health.' },
      { word: 'Autonomous', translation: 'Özerk', icon: '🤖', example: 'Autonomous vehicles are the future.' },
      { word: 'Fundamental', translation: 'Temel', icon: '🏛️', example: 'This is a fundamental principle.' },
      { word: 'Inherent', translation: 'Doğuştan', icon: '🧬', example: 'Risk is inherent in business.' },
      { word: 'Imperative', translation: 'Zorunlu', icon: '❗', example: 'It\'s imperative to act now.' },
      { word: 'Coherent', translation: 'Tutarlı', icon: '🔗', example: 'Present a coherent argument.' },
      { word: 'Arbitrary', translation: 'Keyfi', icon: '🎲', example: 'The decision seems arbitrary.' },
      { word: 'Paradoxical', translation: 'Paradoksal', icon: '♾️', example: 'Life is paradoxical.' },
      { word: 'Exacerbate', translation: 'Kötüleştirmek', icon: '📉', example: 'This will exacerbate the problem.' },
      { word: 'Proliferate', translation: 'Çoğalmak', icon: '📈', example: 'Misinformation proliferates online.' },
      { word: 'Reconcile', translation: 'Uzlaştırmak', icon: '🤝', example: 'They reconciled their differences.' },
      { word: 'Vindicate', translation: 'Haklı çıkarmak', icon: '⚖️', example: 'The evidence will vindicate him.' },
      { word: 'Corroborate', translation: 'Doğrulamak', icon: '✅', example: 'Can you corroborate this claim?' },
    ],
    C2: [
      { word: 'Ephemeral', translation: 'Geçici, kısa ömürlü', icon: '🌅', example: 'Morning dew is ephemeral.' },
      { word: 'Ubiquitous', translation: 'Her yerde bulunan', icon: '🌍', example: 'Smartphones are ubiquitous today.' },
      { word: 'Paradigm', translation: 'Örnek model, paradigma', icon: '🔄', example: 'A paradigm shift in technology.' },
      { word: 'Exacerbate', translation: 'Kötüleştirmek', icon: '📉', example: 'Stress can exacerbate health problems.' },
      { word: 'Nuance', translation: 'İncelik, nüans', icon: '🎨', example: 'There are many nuances in this argument.' },
      { word: 'Conundrum', translation: 'Bilmece', icon: '🧩', example: 'This is a philosophical conundrum.' },
      { word: 'Esoteric', translation: 'Ezoterik', icon: '🔮', example: 'The topic is rather esoteric.' },
      { word: 'Fallacious', translation: 'Aldatıcı', icon: '🎭', example: 'His argument was fallacious.' },
      { word: 'Idiosyncratic', translation: 'Kendine özgü', icon: '🎨', example: 'She has an idiosyncratic style.' },
      { word: 'Juxtaposition', translation: 'Yan yana koyma', icon: '⚖️', example: 'The juxtaposition is striking.' },
      { word: 'Metamorphosis', translation: 'Başkalaşım', icon: '🦋', example: 'The city underwent a metamorphosis.' },
      { word: 'Obfuscate', translation: 'Karıştırmak', icon: '🌫️', example: 'Don\'t obfuscate the issue.' },
      { word: 'Pernicious', translation: 'Zararlı', icon: '☠️', example: 'The effects are pernicious.' },
      { word: 'Quintessential', translation: 'Özün en saf hali', icon: '💎', example: 'He\'s the quintessential gentleman.' },
      { word: 'Recalcitrant', translation: 'İnatçı', icon: '🐂', example: 'The student was recalcitrant.' },
      { word: 'Sycophant', translation: 'Dalkavuk', icon: '🤥', example: 'He\'s nothing but a sycophant.' },
      { word: 'Taciturn', translation: 'Az konuşan', icon: '🤐', example: 'He\'s naturally taciturn.' },
      { word: 'Vicarious', translation: 'Dolaylı', icon: '👁️', example: 'I get vicarious pleasure from books.' },
      { word: 'Zeitgeist', translation: 'Çağın ruhu', icon: '🕰️', example: 'This captures the zeitgeist.' },
      { word: 'Anachronism', translation: 'Çağ dışı', icon: '⏳', example: 'The practice is an anachronism.' },
      { word: 'Dichotomy', translation: 'İkilem', icon: '⚖️', example: 'There\'s a false dichotomy here.' },
      { word: 'Egregious', translation: 'Korkunç', icon: '😱', example: 'That was an egregious error.' },
      { word: 'Hegemony', translation: 'Hegemonya', icon: '👑', example: 'Cultural hegemony is powerful.' },
      { word: 'Ineffable', translation: 'Tarif edilemez', icon: '✨', example: 'The beauty is ineffable.' },
      { word: 'Perfunctory', translation: 'Yüzeysel', icon: '😐', example: 'His response was perfunctory.' },
    ],
  },
  ar: {
    A1: [
      { word: 'مرحبا', translation: 'Merhaba', icon: '👋', example: 'مرحبا، كيف حالك؟' },
      { word: 'شكرا', translation: 'Teşekkür ederim', icon: '🙏', example: 'شكرا لمساعدتك!' },
      { word: 'آسف', translation: 'Özür dilerim', icon: '😔', example: 'أنا آسف على التأخير.' },
      { word: 'من فضلك', translation: 'Lütfen', icon: '🥺', example: 'هل يمكنك مساعدتي من فضلك؟' },
      { word: 'مع السلامة', translation: 'Hoşça kal', icon: '👋', example: 'مع السلامة، أراك غدا!' },
      { word: 'نعم', translation: 'Evet', icon: '✅', example: 'نعم، أنا موافق.' },
      { word: 'لا', translation: 'Hayır', icon: '❌', example: 'لا، لا أريد ذلك.' },
      { word: 'ماء', translation: 'Su', icon: '💧', example: 'هل يمكنني الحصول على بعض الماء؟' },
      { word: 'طعام', translation: 'Yemek', icon: '🍕', example: 'الطعام لذيذ!' },
      { word: 'صديق', translation: 'Arkadaş', icon: '👥', example: 'إنها أفضل صديقة لي.' },
      { word: 'عائلة', translation: 'Aile', icon: '👨‍👩‍👧', example: 'أحب عائلتي.' },
      { word: 'بيت', translation: 'Ev', icon: '🏠', example: 'هذا هو بيتي.' },
      { word: 'كلب', translation: 'Köpek', icon: '🐕', example: 'لدي كلب.' },
      { word: 'قطة', translation: 'Kedi', icon: '🐈', example: 'القطة نائمة.' },
      { word: 'جيد', translation: 'İyi', icon: '👍', example: 'يوم جيد!' },
      { word: 'سيئ', translation: 'Kötü', icon: '👎', example: 'هذه فكرة سيئة.' },
      { word: 'مساعدة', translation: 'Yardım', icon: '🆘', example: 'أحتاج إلى مساعدة!' },
      { word: 'حب', translation: 'Sevmek', icon: '❤️', example: 'أحبك.' },
      { word: 'سعيد', translation: 'Mutlu', icon: '😊', example: 'أنا سعيد جدا اليوم!' },
      { word: 'حزين', translation: 'Üzgün', icon: '😢', example: 'لماذا أنت حزين؟' },
      { word: 'كبير', translation: 'Büyük', icon: '🔷', example: 'هذا بيت كبير!' },
      { word: 'صغير', translation: 'Küçük', icon: '🔹', example: 'هذه سيارة صغيرة.' },
      { word: 'ساخن', translation: 'Sıcak', icon: '🔥', example: 'القهوة ساخنة.' },
      { word: 'بارد', translation: 'Soğuk', icon: '❄️', example: 'الجو بارد في الخارج.' },
      { word: 'عجوز', translation: 'Yaşlı', icon: '👴', example: 'جدي عجوز.' },
    ],
    A2: [
      { word: 'أقدر', translation: 'Takdir etmek', icon: '💖', example: 'أقدر مساعدتك.' },
      { word: 'أفهم', translation: 'Anlamak', icon: '🧠', example: 'هل تفهم السؤال؟' },
      { word: 'مهم', translation: 'Önemli', icon: '⭐', example: 'هذا مهم جدا!' },
      { word: 'مختلف', translation: 'Farklı', icon: '🔄', example: 'كل شخص مختلف.' },
      { word: 'أشرح', translation: 'Açıklamak', icon: '💬', example: 'هل يمكنك شرح هذا لي؟' },
      { word: 'جميل', translation: 'Güzel', icon: '🌺', example: 'يوم جميل!' },
      { word: 'صعب', translation: 'Zor', icon: '😓', example: 'هذا الاختبار صعب.' },
      { word: 'سهل', translation: 'Kolay', icon: '😌', example: 'الامتحان كان سهلا.' },
      { word: 'أتعلم', translation: 'Öğrenmek', icon: '📚', example: 'أريد أن أتعلم الإنجليزية.' },
      { word: 'أعلم', translation: 'Öğretmek', icon: '👨‍🏫', example: 'هل يمكنك أن تعلمني؟' },
      { word: 'أتذكر', translation: 'Hatırlamak', icon: '🧠', example: 'أتذكرك!' },
      { word: 'أنسى', translation: 'Unutmak', icon: '🤔', example: 'لا تنسى مفاتيحك.' },
      { word: 'مشغول', translation: 'Meşgul', icon: '⏰', example: 'أنا مشغول الآن.' },
      { word: 'حر', translation: 'Boş', icon: '🆓', example: 'هل أنت حر غدا؟' },
      { word: 'متعب', translation: 'Yorgun', icon: '😴', example: 'أشعر بالتعب اليوم.' },
      { word: 'قوي', translation: 'Güçlü', icon: '💪', example: 'إنه قوي جدا.' },
      { word: 'ضعيف', translation: 'Zayıf', icon: '😞', example: 'أشعر بالضعف.' },
      { word: 'سريع', translation: 'Hızlı', icon: '⚡', example: 'تلك السيارة سريعة!' },
      { word: 'بطيء', translation: 'Yavaş', icon: '🐢', example: 'من فضلك تحدث ببطء.' },
      { word: 'سؤال', translation: 'Soru', icon: '❓', example: 'لدي سؤال.' },
      { word: 'جواب', translation: 'Cevap', icon: '💡', example: 'هل تعرف الإجابة؟' },
      { word: 'مشكلة', translation: 'Sorun', icon: '⚠️', example: 'لدينا مشكلة.' },
      { word: 'حل', translation: 'Çözüm', icon: '✅', example: 'وجدت الحل!' },
      { word: 'مثير للاهتمام', translation: 'İlginç', icon: '🤨', example: 'هذه قصة مثيرة للاهتمام.' },
      { word: 'ممل', translation: 'Sıkıcı', icon: '😴', example: 'الفيلم كان مملا.' },
    ],
    B1: [
      { word: 'أحقق', translation: 'Başarmak', icon: '🎯', example: 'يمكنك تحقيق أهدافك.' },
      { word: 'أعتبر', translation: 'Düşünmek', icon: '🤔', example: 'سأعتبر عرضك.' },
      { word: 'فائدة', translation: 'Fayda', icon: '✨', example: 'للتمرين فوائد كثيرة.' },
      { word: 'فرصة', translation: 'Fırsat', icon: '🚪', example: 'هذه فرصة رائعة!' },
      { word: 'تحدي', translation: 'Meydan okuma', icon: '💪', example: 'تعلم اللغة الإنجليزية تحدٍ.' },
      { word: 'تطوير', translation: 'Gelişim', icon: '📈', example: 'تطوير الطفل مهم.' },
      { word: 'تجربة', translation: 'Deneyim', icon: '🎓', example: 'لدي 5 سنوات من الخبرة.' },
      { word: 'معرفة', translation: 'Bilgi', icon: '📖', example: 'المعرفة قوة.' },
      { word: 'مهارة', translation: 'Beceri', icon: '🛠️', example: 'التواصل مهارة قيمة.' },
      { word: 'نجاح', translation: 'Başarı', icon: '🏆', example: 'العمل الجاد يؤدي إلى النجاح.' },
      { word: 'فشل', translation: 'Başarısızlık', icon: '❌', example: 'تعلم من فشلك.' },
      { word: 'أحسن', translation: 'İyileştirmek', icon: '⬆️', example: 'أريد تحسين لغتي الإنجليزية.' },
      { word: 'تقدم', translation: 'İlerleme', icon: '📊', example: 'أنت تحرز تقدما كبيرا!' },
      { word: 'جهد', translation: 'Çaba', icon: '💯', example: 'النجاح يتطلب جهدا.' },
      { word: 'صبر', translation: 'Sabır', icon: '⏳', example: 'التعلم يتطلب صبرا.' },
      { word: 'ممارسة', translation: 'Pratik', icon: '🎯', example: 'الممارسة تصنع الكمال.' },
      { word: 'غرض', translation: 'Amaç', icon: '🎯', example: 'ما هو غرضك؟' },
      { word: 'قرار', translation: 'Karar', icon: '🤔', example: 'اتخذ قرارا حكيما.' },
      { word: 'اختيار', translation: 'Seçim', icon: '🔀', example: 'لديك اختيار.' },
      { word: 'طريقة', translation: 'Yöntem', icon: '📋', example: 'هذه أفضل طريقة.' },
      { word: 'عملية', translation: 'Süreç', icon: '⚙️', example: 'ثق في العملية.' },
      { word: 'نتيجة', translation: 'Sonuç', icon: '✅', example: 'النتائج إيجابية.' },
      { word: 'نهج', translation: 'Yaklaşım', icon: '🎯', example: 'جرب نهجا مختلفا.' },
      { word: 'استراتيجية', translation: 'Strateji', icon: '♟️', example: 'نحتاج إلى استراتيجية جديدة.' },
      { word: 'هدف', translation: 'Hedef', icon: '🎯', example: 'ضع أهدافا واقعية.' },
    ],
    B2: [
      { word: 'فعال', translation: 'Verimli', icon: '⚡', example: 'هذه الطريقة فعالة جدا.' },
      { word: 'نتيجة', translation: 'Sonuç', icon: '🔗', example: 'لكل فعل نتائج.' },
      { word: 'مهم', translation: 'Önemli, anlamlı', icon: '🌟', example: 'هذا اكتشاف مهم.' },
      { word: 'أتكيف', translation: 'Uyum sağlamak', icon: '🦎', example: 'يجب أن نتكيف مع التغييرات.' },
      { word: 'منظور', translation: 'Bakış açısı', icon: '👁️', example: 'لكل شخص منظور مختلف.' },
      { word: 'أحلل', translation: 'Analiz etmek', icon: '🔬', example: 'دعنا نحلل البيانات.' },
      { word: 'أقيم', translation: 'Değerlendirmek', icon: '📊', example: 'نحتاج إلى تقييم النتائج.' },
      { word: 'أنفذ', translation: 'Uygulamak', icon: '⚙️', example: 'دعنا ننفذ هذه الخطة.' },
      { word: 'أؤسس', translation: 'Kurmak', icon: '🏢', example: 'نحتاج إلى وضع قواعد.' },
      { word: 'أحافظ', translation: 'Sürdürmek', icon: '🔧', example: 'حافظ على علاقات جيدة.' },
      { word: 'أعزز', translation: 'Geliştirmek', icon: '✨', example: 'هذا سيعزز مهاراتك.' },
      { word: 'أوضح', translation: 'Göstermek', icon: '👉', example: 'دعني أوضح كيف يعمل.' },
      { word: 'أساهم', translation: 'Katkıda bulunmak', icon: '🤝', example: 'يجب على الجميع المساهمة.' },
      { word: 'أشارك', translation: 'Katılmak', icon: '🙋', example: 'يرجى المشاركة في النقاش.' },
      { word: 'أتعاون', translation: 'İşbirliği yapmak', icon: '👥', example: 'نحتاج إلى التعاون في هذا.' },
      { word: 'أفاوض', translation: 'Müzakere etmek', icon: '🤝', example: 'دعنا نتفاوض على الشروط.' },
      { word: 'أحقق', translation: 'Araştırmak', icon: '🔍', example: 'سيحققون في القضية.' },
      { word: 'أحدد', translation: 'Belirlemek', icon: '🎯', example: 'يجب أن نحدد السبب.' },
      { word: 'أشير', translation: 'Belirtmek', icon: '👆', example: 'تشير النتائج إلى النجاح.' },
      { word: 'أوضح', translation: 'Göstermek', icon: '📊', example: 'هذا المثال يوضح النقطة.' },
      { word: 'أؤكد', translation: 'Vurgulamak', icon: '‼️', example: 'أريد التأكيد على هذه النقطة.' },
      { word: 'أعترف', translation: 'Kabul etmek', icon: '✅', example: 'نعترف بالمشكلة.' },
      { word: 'أتعرف', translation: 'Tanımak', icon: '👀', example: 'أتعرف على هذا النمط.' },
      { word: 'أسهل', translation: 'Kolaylaştırmak', icon: '🔓', example: 'هذا سيسهل التعلم.' },
      { word: 'أدمج', translation: 'Entegre etmek', icon: '🔗', example: 'نحتاج إلى دمج هذه الأنظمة.' },
    ],
    C1: [
      { word: 'حتمي', translation: 'Kaçınılmaz', icon: '⏰', example: 'التغيير حتمي.' },
      { word: 'أفهم', translation: 'Kavramak', icon: '🧩', example: 'من الصعب فهم التعقيد.' },
      { word: 'عميق', translation: 'Derin, etkileyici', icon: '🌊', example: 'كان له تأثير عميق على المجتمع.' },
      { word: 'غامض', translation: 'Belirsiz, muğlak', icon: '❓', example: 'الرسالة كانت غامضة.' },
      { word: 'مرن', translation: 'Dayanıklı', icon: '🛡️', example: 'إنها مرنة جدا تحت الضغط.' },
      { word: 'مثير للجدل', translation: 'Tartışmalı', icon: '⚔️', example: 'هذه قضية مثيرة للجدل.' },
      { word: 'معقد', translation: 'Karmaşık', icon: '🕸️', example: 'التصميم معقد.' },
      { word: 'فصيح', translation: 'Belagatli', icon: '🗣️', example: 'ألقت خطابا فصيحا.' },
      { word: 'دقيق', translation: 'Titiz', icon: '🔍', example: 'إنه دقيق في عمله.' },
      { word: 'واقعي', translation: 'Pragmatik', icon: '⚙️', example: 'نحتاج إلى حل واقعي.' },
      { word: 'مقنع', translation: 'İlgi çekici', icon: '🎭', example: 'هذه حجة مقنعة.' },
      { word: 'كبير', translation: 'Önemli', icon: '💰', example: 'هناك أدلة كبيرة.' },
      { word: 'ضار', translation: 'Zararlı', icon: '☠️', example: 'التدخين ضار بالصحة.' },
      { word: 'مستقل', translation: 'Özerk', icon: '🤖', example: 'السيارات المستقلة هي المستقبل.' },
      { word: 'أساسي', translation: 'Temel', icon: '🏛️', example: 'هذا مبدأ أساسي.' },
      { word: 'متأصل', translation: 'Doğuştan', icon: '🧬', example: 'المخاطرة متأصلة في الأعمال.' },
      { word: 'ضروري', translation: 'Zorunlu', icon: '❗', example: 'من الضروري التصرف الآن.' },
      { word: 'متماسك', translation: 'Tutarlı', icon: '🔗', example: 'قدم حجة متماسكة.' },
      { word: 'تعسفي', translation: 'Keyfi', icon: '🎲', example: 'القرار يبدو تعسفيا.' },
      { word: 'متناقض', translation: 'Paradoksal', icon: '♾️', example: 'الحياة متناقضة.' },
      { word: 'أزيد سوءا', translation: 'Kötüleştirmek', icon: '📉', example: 'هذا سيزيد المشكلة سوءا.' },
      { word: 'أتكاثر', translation: 'Çoğalmak', icon: '📈', example: 'المعلومات المضللة تتكاثر على الإنترنت.' },
      { word: 'أوفق', translation: 'Uzlaştırmak', icon: '🤝', example: 'وفقوا بين خلافاتهم.' },
      { word: 'أبرئ', translation: 'Haklı çıkarmak', icon: '⚖️', example: 'الأدلة ستبرئه.' },
      { word: 'أؤكد', translation: 'Doğrulamak', icon: '✅', example: 'هل يمكنك تأكيد هذا الادعاء؟' },
    ],
    C2: [
      { word: 'زائل', translation: 'Geçici, kısa ömürlü', icon: '🌅', example: 'ندى الصباح زائل.' },
      { word: 'منتشر', translation: 'Her yerde bulunan', icon: '🌍', example: 'الهواتف الذكية منتشرة اليوم.' },
      { word: 'نموذج', translation: 'Örnek model, paradigma', icon: '🔄', example: 'تحول نموذجي في التكنولوجيا.' },
      { word: 'أزيد سوءا', translation: 'Kötüleştirmek', icon: '📉', example: 'الإجهاد يمكن أن يزيد المشاكل الصحية سوءا.' },
      { word: 'دقة', translation: 'İncelik, nüans', icon: '🎨', example: 'هناك العديد من الدقائق في هذه الحجة.' },
      { word: 'لغز', translation: 'Bilmece', icon: '🧩', example: 'هذا لغز فلسفي.' },
      { word: 'باطني', translation: 'Ezoterik', icon: '🔮', example: 'الموضوع باطني إلى حد ما.' },
      { word: 'خادع', translation: 'Aldatıcı', icon: '🎭', example: 'حجته كانت خادعة.' },
      { word: 'خاص', translation: 'Kendine özgü', icon: '🎨', example: 'لديها أسلوب خاص.' },
      { word: 'تجاور', translation: 'Yan yana koyma', icon: '⚖️', example: 'التجاور مذهل.' },
      { word: 'تحول', translation: 'Başkalaşım', icon: '🦋', example: 'المدينة خضعت لتحول.' },
      { word: 'أبهم', translation: 'Karıştırmak', icon: '🌫️', example: 'لا تبهم المسألة.' },
      { word: 'خبيث', translation: 'Zararlı', icon: '☠️', example: 'الآثار خبيثة.' },
      { word: 'جوهري', translation: 'Özün en saf hali', icon: '💎', example: 'إنه الرجل النبيل الجوهري.' },
      { word: 'عنيد', translation: 'İnatçı', icon: '🐂', example: 'كان الطالب عنيدا.' },
      { word: 'متملق', translation: 'Dalkavuk', icon: '🤥', example: 'إنه ليس سوى متملق.' },
      { word: 'قليل الكلام', translation: 'Az konuşan', icon: '🤐', example: 'إنه قليل الكلام بطبيعته.' },
      { word: 'غير مباشر', translation: 'Dolaylı', icon: '👁️', example: 'أحصل على متعة غير مباشرة من الكتب.' },
      { word: 'روح العصر', translation: 'Çağın ruhu', icon: '🕰️', example: 'هذا يلتقط روح العصر.' },
      { word: 'مفارقة زمنية', translation: 'Çağ dışı', icon: '⏳', example: 'الممارسة مفارقة زمنية.' },
      { word: 'ازدواجية', translation: 'İkilem', icon: '⚖️', example: 'هناك ازدواجية خاطئة هنا.' },
      { word: 'فاحش', translation: 'Korkunç', icon: '😱', example: 'كان ذلك خطأ فاحشا.' },
      { word: 'هيمنة', translation: 'Hegemonya', icon: '👑', example: 'الهيمنة الثقافية قوية.' },
      { word: 'لا يوصف', translation: 'Tarif edilemez', icon: '✨', example: 'الجمال لا يوصف.' },
      { word: 'سطحي', translation: 'Yüzeysel', icon: '😐', example: 'كان رده سطحيا.' },
    ],
  },
  ru: {
    A1: [
      { word: 'Привет', translation: 'Merhaba', icon: '👋', example: 'Привет, как дела?' },
      { word: 'Спасибо', translation: 'Teşekkür ederim', icon: '🙏', example: 'Спасибо за помощь!' },
      { word: 'Извините', translation: 'Özür dilerim', icon: '😔', example: 'Извините за опоздание.' },
      { word: 'Пожалуйста', translation: 'Lütfen', icon: '🥺', example: 'Можете мне помочь, пожалуйста?' },
      { word: 'До свидания', translation: 'Hoşça kal', icon: '👋', example: 'До свидания, увидимся завтра!' },
      { word: 'Да', translation: 'Evet', icon: '✅', example: 'Да, я согласен.' },
      { word: 'Нет', translation: 'Hayır', icon: '❌', example: 'Нет, я не хочу этого.' },
      { word: 'Вода', translation: 'Su', icon: '💧', example: 'Можно мне воды?' },
      { word: 'Еда', translation: 'Yemek', icon: '🍕', example: 'Еда вкусная!' },
      { word: 'Друг', translation: 'Arkadaş', icon: '👥', example: 'Она мой лучший друг.' },
      { word: 'Семья', translation: 'Aile', icon: '👨‍👩‍👧', example: 'Я люблю свою семью.' },
      { word: 'Дом', translation: 'Ev', icon: '🏠', example: 'Это мой дом.' },
      { word: 'Собака', translation: 'Köpek', icon: '🐕', example: 'У меня есть собака.' },
      { word: 'Кошка', translation: 'Kedi', icon: '🐈', example: 'Кошка спит.' },
      { word: 'Хорошо', translation: 'İyi', icon: '👍', example: 'Хорошего дня!' },
      { word: 'Плохо', translation: 'Kötü', icon: '👎', example: 'Это плохая идея.' },
      { word: 'Помощь', translation: 'Yardım', icon: '🆘', example: 'Мне нужна помощь!' },
      { word: 'Любовь', translation: 'Sevmek', icon: '❤️', example: 'Я люблю тебя.' },
      { word: 'Счастливый', translation: 'Mutlu', icon: '😊', example: 'Я так счастлив сегодня!' },
      { word: 'Грустный', translation: 'Üzgün', icon: '😢', example: 'Почему ты грустный?' },
      { word: 'Большой', translation: 'Büyük', icon: '🔷', example: 'Это большой дом!' },
      { word: 'Маленький', translation: 'Küçük', icon: '🔹', example: 'Это маленькая машина.' },
      { word: 'Горячий', translation: 'Sıcak', icon: '🔥', example: 'Кофе горячий.' },
      { word: 'Холодный', translation: 'Soğuk', icon: '❄️', example: 'На улице холодно.' },
      { word: 'Старый', translation: 'Yaşlı', icon: '👴', example: 'Мой дедушка старый.' },
    ],
    A2: [
      { word: 'Ценить', translation: 'Takdir etmek', icon: '💖', example: 'Я ценю вашу помощь.' },
      { word: 'Понимать', translation: 'Anlamak', icon: '🧠', example: 'Вы понимаете вопрос?' },
      { word: 'Важный', translation: 'Önemli', icon: '⭐', example: 'Это очень важно!' },
      { word: 'Разный', translation: 'Farklı', icon: '🔄', example: 'Все люди разные.' },
      { word: 'Объяснить', translation: 'Açıklamak', icon: '💬', example: 'Можете объяснить мне это?' },
      { word: 'Красивый', translation: 'Güzel', icon: '🌺', example: 'Какой красивый день!' },
      { word: 'Трудный', translation: 'Zor', icon: '😓', example: 'Этот тест трудный.' },
      { word: 'Лёгкий', translation: 'Kolay', icon: '😌', example: 'Экзамен был лёгким.' },
      { word: 'Учиться', translation: 'Öğrenmek', icon: '📚', example: 'Я хочу учить английский.' },
      { word: 'Учить', translation: 'Öğretmek', icon: '👨‍🏫', example: 'Можете меня научить?' },
      { word: 'Помнить', translation: 'Hatırlamak', icon: '🧠', example: 'Я помню тебя!' },
      { word: 'Забыть', translation: 'Unutmak', icon: '🤔', example: 'Не забудь ключи.' },
      { word: 'Занятый', translation: 'Meşgul', icon: '⏰', example: 'Я сейчас занят.' },
      { word: 'Свободный', translation: 'Boş', icon: '🆓', example: 'Ты свободен завтра?' },
      { word: 'Уставший', translation: 'Yorgun', icon: '😴', example: 'Я чувствую себя уставшим сегодня.' },
      { word: 'Сильный', translation: 'Güçlü', icon: '💪', example: 'Он очень сильный.' },
      { word: 'Слабый', translation: 'Zayıf', icon: '😞', example: 'Я чувствую себя слабым.' },
      { word: 'Быстрый', translation: 'Hızlı', icon: '⚡', example: 'Эта машина быстрая!' },
      { word: 'Медленный', translation: 'Yavaş', icon: '🐢', example: 'Пожалуйста, говорите медленно.' },
      { word: 'Вопрос', translation: 'Soru', icon: '❓', example: 'У меня есть вопрос.' },
      { word: 'Ответ', translation: 'Cevap', icon: '💡', example: 'Вы знаете ответ?' },
      { word: 'Проблема', translation: 'Sorun', icon: '⚠️', example: 'У нас проблема.' },
      { word: 'Решение', translation: 'Çözüm', icon: '✅', example: 'Я нашёл решение!' },
      { word: 'Интересный', translation: 'İlginç', icon: '🤨', example: 'Это интересная история.' },
      { word: 'Скучный', translation: 'Sıkıcı', icon: '😴', example: 'Фильм был скучным.' },
    ],
    B1: [
      { word: 'Достигать', translation: 'Başarmak', icon: '🎯', example: 'Вы можете достичь своих целей.' },
      { word: 'Рассматривать', translation: 'Düşünmek', icon: '🤔', example: 'Я рассмотрю ваше предложение.' },
      { word: 'Польза', translation: 'Fayda', icon: '✨', example: 'У упражнений много пользы.' },
      { word: 'Возможность', translation: 'Fırsat', icon: '🚪', example: 'Это отличная возможность!' },
      { word: 'Вызов', translation: 'Meydan okuma', icon: '💪', example: 'Изучение английского - это вызов.' },
      { word: 'Развитие', translation: 'Gelişim', icon: '📈', example: 'Развитие детей важно.' },
      { word: 'Опыт', translation: 'Deneyim', icon: '🎓', example: 'У меня 5 лет опыта.' },
      { word: 'Знание', translation: 'Bilgi', icon: '📖', example: 'Знание - сила.' },
      { word: 'Навык', translation: 'Beceri', icon: '🛠️', example: 'Общение - ценный навык.' },
      { word: 'Успех', translation: 'Başarı', icon: '🏆', example: 'Тяжёлая работа ведёт к успеху.' },
      { word: 'Неудача', translation: 'Başarısızlık', icon: '❌', example: 'Учись на своих неудачах.' },
      { word: 'Улучшать', translation: 'İyileştirmek', icon: '⬆️', example: 'Я хочу улучшить свой английский.' },
      { word: 'Прогресс', translation: 'İlerleme', icon: '📊', example: 'Ты делаешь большой прогресс!' },
      { word: 'Усилие', translation: 'Çaba', icon: '💯', example: 'Успех требует усилий.' },
      { word: 'Терпение', translation: 'Sabır', icon: '⏳', example: 'Обучение требует терпения.' },
      { word: 'Практика', translation: 'Pratik', icon: '🎯', example: 'Практика делает совершенным.' },
      { word: 'Цель', translation: 'Amaç', icon: '🎯', example: 'Какова ваша цель?' },
      { word: 'Решение', translation: 'Karar', icon: '🤔', example: 'Примите мудрое решение.' },
      { word: 'Выбор', translation: 'Seçim', icon: '🔀', example: 'У тебя есть выбор.' },
      { word: 'Метод', translation: 'Yöntem', icon: '📋', example: 'Это лучший метод.' },
      { word: 'Процесс', translation: 'Süreç', icon: '⚙️', example: 'Доверяй процессу.' },
      { word: 'Результат', translation: 'Sonuç', icon: '✅', example: 'Результаты положительные.' },
      { word: 'Подход', translation: 'Yaklaşım', icon: '🎯', example: 'Попробуй другой подход.' },
      { word: 'Стратегия', translation: 'Strateji', icon: '♟️', example: 'Нам нужна новая стратегия.' },
      { word: 'Цель', translation: 'Hedef', icon: '🎯', example: 'Ставь реалистичные цели.' },
    ],
    B2: [
      { word: 'Эффективный', translation: 'Verimli', icon: '⚡', example: 'Этот метод очень эффективен.' },
      { word: 'Последствие', translation: 'Sonuç', icon: '🔗', example: 'У каждого действия есть последствия.' },
      { word: 'Значительный', translation: 'Önemli, anlamlı', icon: '🌟', example: 'Это значительное открытие.' },
      { word: 'Адаптироваться', translation: 'Uyum sağlamak', icon: '🦎', example: 'Мы должны адаптироваться к изменениям.' },
      { word: 'Перспектива', translation: 'Bakış açısı', icon: '👁️', example: 'У всех разная перспектива.' },
      { word: 'Анализировать', translation: 'Analiz etmek', icon: '🔬', example: 'Давайте проанализируем данные.' },
      { word: 'Оценивать', translation: 'Değerlendirmek', icon: '📊', example: 'Нам нужно оценить результаты.' },
      { word: 'Внедрять', translation: 'Uygulamak', icon: '⚙️', example: 'Давайте внедрим этот план.' },
      { word: 'Устанавливать', translation: 'Kurmak', icon: '🏢', example: 'Нам нужно установить правила.' },
      { word: 'Поддерживать', translation: 'Sürdürmek', icon: '🔧', example: 'Поддерживай хорошие отношения.' },
      { word: 'Улучшать', translation: 'Geliştirmek', icon: '✨', example: 'Это улучшит твои навыки.' },
      { word: 'Демонстрировать', translation: 'Göstermek', icon: '👉', example: 'Позволь мне продемонстрировать, как это работает.' },
      { word: 'Содействовать', translation: 'Katkıda bulunmak', icon: '🤝', example: 'Все должны содействовать.' },
      { word: 'Участвовать', translation: 'Katılmak', icon: '🙋', example: 'Пожалуйста, участвуйте в обсуждении.' },
      { word: 'Сотрудничать', translation: 'İşbirliği yapmak', icon: '👥', example: 'Нам нужно сотрудничать по этому вопросу.' },
      { word: 'Договариваться', translation: 'Müzakere etmek', icon: '🤝', example: 'Давайте договоримся об условиях.' },
      { word: 'Расследовать', translation: 'Araştırmak', icon: '🔍', example: 'Они будут расследовать дело.' },
      { word: 'Определять', translation: 'Belirlemek', icon: '🎯', example: 'Мы должны определить причину.' },
      { word: 'Указывать', translation: 'Belirtmek', icon: '👆', example: 'Результаты указывают на успех.' },
      { word: 'Иллюстрировать', translation: 'Göstermek', icon: '📊', example: 'Этот пример иллюстрирует точку зрения.' },
      { word: 'Подчёркивать', translation: 'Vurgulamak', icon: '‼️', example: 'Я хочу подчеркнуть этот момент.' },
      { word: 'Признавать', translation: 'Kabul etmek', icon: '✅', example: 'Мы признаём проблему.' },
      { word: 'Распознавать', translation: 'Tanımak', icon: '👀', example: 'Я распознаю этот паттерн.' },
      { word: 'Облегчать', translation: 'Kolaylaştırmak', icon: '🔓', example: 'Это облегчит обучение.' },
      { word: 'Интегрировать', translation: 'Entegre etmek', icon: '🔗', example: 'Нам нужно интегрировать эти системы.' },
    ],
    C1: [
      { word: 'Неизбежный', translation: 'Kaçınılmaz', icon: '⏰', example: 'Изменения неизбежны.' },
      { word: 'Постигать', translation: 'Kavramak', icon: '🧩', example: 'Трудно постигнуть сложность.' },
      { word: 'Глубокий', translation: 'Derin, etkileyici', icon: '🌊', example: 'Он оказал глубокое влияние на общество.' },
      { word: 'Неоднозначный', translation: 'Belirsiz, muğlak', icon: '❓', example: 'Сообщение было неоднозначным.' },
      { word: 'Устойчивый', translation: 'Dayanıklı', icon: '🛡️', example: 'Она очень устойчива под давлением.' },
      { word: 'Спорный', translation: 'Tartışmalı', icon: '⚔️', example: 'Это спорный вопрос.' },
      { word: 'Сложный', translation: 'Karmaşık', icon: '🕸️', example: 'Дизайн сложный.' },
      { word: 'Красноречивый', translation: 'Belagatli', icon: '🗣️', example: 'Она произнесла красноречивую речь.' },
      { word: 'Дотошный', translation: 'Titiz', icon: '🔍', example: 'Он дотошен в своей работе.' },
      { word: 'Прагматичный', translation: 'Pragmatik', icon: '⚙️', example: 'Нам нужно прагматичное решение.' },
      { word: 'Убедительный', translation: 'İlgi çekici', icon: '🎭', example: 'Это убедительный аргумент.' },
      { word: 'Существенный', translation: 'Önemli', icon: '💰', example: 'Есть существенные доказательства.' },
      { word: 'Вредный', translation: 'Zararlı', icon: '☠️', example: 'Курение вредно для здоровья.' },
      { word: 'Автономный', translation: 'Özerk', icon: '🤖', example: 'Автономные транспортные средства - это будущее.' },
      { word: 'Фундаментальный', translation: 'Temel', icon: '🏛️', example: 'Это фундаментальный принцип.' },
      { word: 'Врождённый', translation: 'Doğuştan', icon: '🧬', example: 'Риск присущ бизнесу.' },
      { word: 'Императивный', translation: 'Zorunlu', icon: '❗', example: 'Необходимо действовать сейчас.' },
      { word: 'Связный', translation: 'Tutarlı', icon: '🔗', example: 'Представь связный аргумент.' },
      { word: 'Произвольный', translation: 'Keyfi', icon: '🎲', example: 'Решение кажется произвольным.' },
      { word: 'Парадоксальный', translation: 'Paradoksal', icon: '♾️', example: 'Жизнь парадоксальна.' },
      { word: 'Обострять', translation: 'Kötüleştirmek', icon: '📉', example: 'Это обострит проблему.' },
      { word: 'Распространяться', translation: 'Çoğalmak', icon: '📈', example: 'Дезинформация распространяется онлайн.' },
      { word: 'Примирять', translation: 'Uzlaştırmak', icon: '🤝', example: 'Они примирили свои разногласия.' },
      { word: 'Оправдывать', translation: 'Haklı çıkarmak', icon: '⚖️', example: 'Доказательства его оправдают.' },
      { word: 'Подтверждать', translation: 'Doğrulamak', icon: '✅', example: 'Можете подтвердить это утверждение?' },
    ],
    C2: [
      { word: 'Эфемерный', translation: 'Geçici, kısa ömürlü', icon: '🌅', example: 'Утренняя роса эфемерна.' },
      { word: 'Вездесущий', translation: 'Her yerde bulunan', icon: '🌍', example: 'Смартфоны вездесущи сегодня.' },
      { word: 'Парадигма', translation: 'Örnek model, paradigma', icon: '🔄', example: 'Сдвиг парадигмы в технологии.' },
      { word: 'Усугублять', translation: 'Kötüleştirmek', icon: '📉', example: 'Стресс может усугубить проблемы со здоровьем.' },
      { word: 'Нюанс', translation: 'İncelik, nüans', icon: '🎨', example: 'В этом аргументе много нюансов.' },
      { word: 'Головоломка', translation: 'Bilmece', icon: '🧩', example: 'Это философская головоломка.' },
      { word: 'Эзотерический', translation: 'Ezoterik', icon: '🔮', example: 'Тема довольно эзотерическая.' },
      { word: 'Ошибочный', translation: 'Aldatıcı', icon: '🎭', example: 'Его аргумент был ошибочным.' },
      { word: 'Идиосинкратический', translation: 'Kendine özgü', icon: '🎨', example: 'У неё идиосинкратический стиль.' },
      { word: 'Сопоставление', translation: 'Yan yana koyma', icon: '⚖️', example: 'Сопоставление поразительно.' },
      { word: 'Метаморфоза', translation: 'Başkalaşım', icon: '🦋', example: 'Город претерпел метаморфозу.' },
      { word: 'Запутывать', translation: 'Karıştırmak', icon: '🌫️', example: 'Не запутывай проблему.' },
      { word: 'Пагубный', translation: 'Zararlı', icon: '☠️', example: 'Эффекты пагубны.' },
      { word: 'Квинтэссенция', translation: 'Özün en saf hali', icon: '💎', example: 'Он квинтэссенция джентльмена.' },
      { word: 'Непокорный', translation: 'İnatçı', icon: '🐂', example: 'Студент был непокорным.' },
      { word: 'Подхалим', translation: 'Dalkavuk', icon: '🤥', example: 'Он не более чем подхалим.' },
      { word: 'Молчаливый', translation: 'Az konuşan', icon: '🤐', example: 'Он от природы молчалив.' },
      { word: 'Опосредованный', translation: 'Dolaylı', icon: '👁️', example: 'Я получаю опосредованное удовольствие от книг.' },
      { word: 'Дух времени', translation: 'Çağın ruhu', icon: '🕰️', example: 'Это отражает дух времени.' },
      { word: 'Анахронизм', translation: 'Çağ dışı', icon: '⏳', example: 'Эта практика - анахронизм.' },
      { word: 'Дихотомия', translation: 'İkilem', icon: '⚖️', example: 'Здесь ложная дихотомия.' },
      { word: 'Вопиющий', translation: 'Korkunç', icon: '😱', example: 'Это была вопиющая ошибка.' },
      { word: 'Гегемония', translation: 'Hegemonya', icon: '👑', example: 'Культурная гегемония мощна.' },
      { word: 'Невыразимый', translation: 'Tarif edilemez', icon: '✨', example: 'Красота невыразима.' },
      { word: 'Поверхностный', translation: 'Yüzeysel', icon: '😐', example: 'Его ответ был поверхностным.' },
    ],
  },
};
