#!/bin/bash
# Xcode Build Phase Cycle Fix Script
# This script provides instructions to fix the Sentry upload build phase order

echo "═══════════════════════════════════════════════════════════════"
echo "🔧 XCODE BUILD PHASE CYCLE FIX"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "❌ SORUN: Sentry Upload script build cycle oluşturuyor"
echo ""
echo "✅ ÇÖZÜM: Build phase sırasını düzelt"
echo ""
echo "📋 ADIMLAR:"
echo ""
echo "1. Xcode'u aç:"
echo "   open ios/kspeaker.xcworkspace"
echo ""
echo "2. Sol panelde 'kspeaker' projesine tıkla"
echo ""
echo "3. 'Build Phases' tab'ına git"
echo ""
echo "4. 'Upload dSYMs to Sentry' scriptini bul"
echo ""
echo "5. Bu scripti SÜRÜKLE ve 'Bundle React Native code and images' scriptinin"
echo "   HEMEN ALTINA YERLEŞTİR (Sources ve Frameworks'den sonra olmalı)"
echo ""
echo "6. Yeni sıralama şöyle olmalı:"
echo "   - [CP] Check Pods Manifest.lock"
echo "   - Sources"
echo "   - Frameworks"  
echo "   - Resources"
echo "   - Bundle React Native code and images"
echo "   - Upload dSYMs to Sentry ← BURAYA TAŞI"
echo "   - [CP] Embed Pods Frameworks"
echo "   - [CP] Copy Pods Resources"
echo ""
echo "7. Cmd+B ile build yap"
echo ""
echo "═══════════════════════════════════════════════════════════════"
